services:
  - type: web
    name: cartridge-collection
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn cartridge_collection.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: cartridge-db
          property: connectionString

databases:
  - name: cartridge-db
    plan: starter