services:
  - type: web
    name: curtis-ammo
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn cartridge_collection.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: cartridge-collection-db
          property: connectionString
    disk:
      name: media-disk
      mountPath: /opt/render/project/src/media
      sizeGB: 1

databases:
  - name: cartridge-collection-db
    plan: starter