# Generated by Django 5.1.7 on 2025-03-21 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_common', models.BooleanField(default=False)),
                ('legacy_mappings', models.TextField(blank=True, help_text='Comma-separated list of legacy values that map to this')),
            ],
            options={
                'ordering': ['-is_common', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Caliber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_common', models.BooleanField(default=False)),
                ('legacy_mappings', models.TextField(blank=True, help_text='Comma-separated list of legacy values that map to this')),
            ],
            options={
                'ordering': ['-is_common', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Headstamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Headstamp Code')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Headstamp Name')),
                ('cc', models.IntegerField(choices=[(1, '1 - In Collection'), (2, '2 - Reliable Reference'), (3, '3 - Secondary Source'), (4, '4 - Questionable'), (5, '5 - Unverified')], default=1, verbose_name='Credibility Code')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='headstamps/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['manufacturer__country__name', 'manufacturer__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='LoadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_common', models.BooleanField(default=False)),
                ('legacy_mappings', models.TextField(blank=True, help_text='Comma-separated list of legacy values that map to this')),
            ],
            options={
                'ordering': ['-is_common', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='PAColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_common', models.BooleanField(default=False)),
                ('legacy_mappings', models.TextField(blank=True, help_text='Comma-separated list of legacy values that map to this')),
            ],
            options={
                'ordering': ['-is_common', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='PrimerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('is_common', models.BooleanField(default=False)),
                ('legacy_mappings', models.TextField(blank=True, help_text='Comma-separated list of legacy values that map to this')),
            ],
            options={
                'ordering': ['-is_common', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Source Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cc', models.IntegerField(choices=[(1, '1 - In Collection'), (2, '2 - Reliable Reference'), (3, '3 - Secondary Source'), (4, '4 - Questionable'), (5, '5 - Unverified')], default=1, verbose_name='Credibility Code')),
                ('col_date', models.DateField(blank=True, null=True, verbose_name='Collection Date')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price/Value')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artifacts/')),
                ('bid', models.CharField(max_length=20, unique=True, verbose_name='Box ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Physical Location')),
                ('art_type', models.CharField(choices=[('box', 'Box'), ('photo', 'Photograph'), ('drawing', 'Drawing'), ('label', 'Label'), ('document', 'Document'), ('other', 'Other')], default='box', max_length=50, verbose_name='Artifact Type')),
                ('art_type_other', models.CharField(blank=True, help_text="Specify if 'Other' is selected", max_length=100, null=True, verbose_name='Other Artifact Type')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['bid'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Country Code/Name')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Country Name')),
                ('caliber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.caliber')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cc', models.IntegerField(choices=[(1, '1 - In Collection'), (2, '2 - Reliable Reference'), (3, '3 - Secondary Source'), (4, '4 - Questionable'), (5, '5 - Unverified')], default=1, verbose_name='Credibility Code')),
                ('col_date', models.DateField(blank=True, null=True, verbose_name='Collection Date')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price/Value')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artifacts/')),
                ('cart_id', models.CharField(max_length=20, unique=True, verbose_name='Cartridge ID')),
                ('is_magnetic', models.BooleanField(default=False, verbose_name='Is Magnetic')),
                ('bullet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='collection.bullettype')),
                ('case_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='collection.casetype')),
                ('headstamp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='collection.headstamp')),
                ('load_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='collection.loadtype')),
                ('pa_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='collection.pacolor')),
                ('primer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loads', to='collection.primertype')),
            ],
            options={
                'ordering': ['headstamp__manufacturer__country__name', 'headstamp__code', 'cart_id'],
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cc', models.IntegerField(choices=[(1, '1 - In Collection'), (2, '2 - Reliable Reference'), (3, '3 - Secondary Source'), (4, '4 - Questionable'), (5, '5 - Unverified')], default=1, verbose_name='Credibility Code')),
                ('col_date', models.DateField(blank=True, null=True, verbose_name='Collection Date')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price/Value')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artifacts/')),
                ('cart_id', models.CharField(max_length=20, unique=True, verbose_name='Date/Lot ID')),
                ('year', models.CharField(blank=True, max_length=10, null=True, verbose_name='Year')),
                ('lot_month', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lot/Month')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dates', to='collection.load')),
            ],
            options={
                'ordering': ['load__headstamp__manufacturer__country__name', 'load__cart_id', 'year', 'lot_month'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('code', models.CharField(max_length=100, verbose_name='Manufacturer Code')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manufacturer Name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.country')),
            ],
            options={
                'ordering': ['country__name', 'code'],
                'unique_together': {('code', 'country')},
            },
        ),
        migrations.AddField(
            model_name='headstamp',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='headstamps', to='collection.manufacturer'),
        ),
        migrations.AddField(
            model_name='headstamp',
            name='primary_manufacturer',
            field=models.ForeignKey(blank=True, help_text='Manufacturer who produced the case', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_headstamps', to='collection.manufacturer'),
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cc', models.IntegerField(choices=[(1, '1 - In Collection'), (2, '2 - Reliable Reference'), (3, '3 - Secondary Source'), (4, '4 - Questionable'), (5, '5 - Unverified')], default=1, verbose_name='Credibility Code')),
                ('col_date', models.DateField(blank=True, null=True, verbose_name='Collection Date')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price/Value')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='artifacts/')),
                ('cart_id', models.CharField(max_length=20, unique=True, verbose_name='Variation ID')),
                ('date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='date_variations', to='collection.date')),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='load_variations', to='collection.load')),
            ],
            options={
                'ordering': ['cart_id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='headstamp',
            unique_together={('code', 'manufacturer')},
        ),
        migrations.CreateModel(
            name='LoadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sourced', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.load')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.source')),
            ],
            options={
                'unique_together': {('load', 'source')},
            },
        ),
        migrations.CreateModel(
            name='HeadstampSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sourced', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('headstamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.headstamp')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.source')),
            ],
            options={
                'unique_together': {('headstamp', 'source')},
            },
        ),
        migrations.CreateModel(
            name='DateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sourced', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.date')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.source')),
            ],
            options={
                'unique_together': {('date', 'source')},
            },
        ),
        migrations.CreateModel(
            name='BoxSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sourced', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.box')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.source')),
            ],
            options={
                'unique_together': {('box', 'source')},
            },
        ),
        migrations.CreateModel(
            name='VariationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sourced', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.source')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.variation')),
            ],
            options={
                'unique_together': {('variation', 'source')},
            },
        ),
    ]
