# Generated by Django 5.1.7 on 2025-03-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caliber',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='caliber',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='calibers/'),
        ),
        migrations.AddField(
            model_name='caliber',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order on landing page'),
        ),
        migrations.AddField(
            model_name='caliber',
            name='theme_color',
            field=models.CharField(blank=True, help_text='Hex color code, e.g. #3a7ca5', max_length=20, null=True),
        ),
    ]
