# Generated by Django 5.1.7 on 2025-03-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_caliber_options_caliber_image_caliber_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='box',
            name='col_date',
        ),
        migrations.RemoveField(
            model_name='date',
            name='col_date',
        ),
        migrations.RemoveField(
            model_name='load',
            name='col_date',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='col_date',
        ),
        migrations.AddField(
            model_name='box',
            name='acquisition_note',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Acqu. Note'),
        ),
        migrations.AddField(
            model_name='date',
            name='acquisition_note',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Acqu. Note'),
        ),
        migrations.AddField(
            model_name='load',
            name='acquisition_note',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Acqu. Note'),
        ),
        migrations.AddField(
            model_name='variation',
            name='acquisition_note',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Acqu. Note'),
        ),
        migrations.AlterField(
            model_name='box',
            name='cc',
            field=models.IntegerField(choices=[(1, '1 - In Collection'), (2, '2 - Verified Reference'), (3, '3 - Secondary Source'), (4, '4 - Questionable'), (5, '5 - Unverified')], default=1, verbose_name='Credibility Code'),
        ),
        migrations.AlterField(
            model_name='date',
            name='cc',
            field=models.IntegerField(choices=[(1, '1 - In Collection'), (2, '2 - Verified Reference'), (3, '3 - Secondary Source'), (4, '4 - Questionable'), (5, '5 - Unverified')], default=1, verbose_name='Credibility Code'),
        ),
        migrations.AlterField(
            model_name='headstamp',
            name='cc',
            field=models.IntegerField(choices=[(1, '1 - In Collection'), (2, '2 - Verified Reference'), (3, '3 - Secondary Source'), (4, '4 - Questionable'), (5, '5 - Unverified')], default=1, verbose_name='Credibility Code'),
        ),
        migrations.AlterField(
            model_name='load',
            name='cc',
            field=models.IntegerField(choices=[(1, '1 - In Collection'), (2, '2 - Verified Reference'), (3, '3 - Secondary Source'), (4, '4 - Questionable'), (5, '5 - Unverified')], default=1, verbose_name='Credibility Code'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='cc',
            field=models.IntegerField(choices=[(1, '1 - In Collection'), (2, '2 - Verified Reference'), (3, '3 - Secondary Source'), (4, '4 - Questionable'), (5, '5 - Unverified')], default=1, verbose_name='Credibility Code'),
        ),
    ]
