# Generated by Django 5.1.7 on 2025-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_collectioninfo_remove_box_col_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioninfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
