# Generated by Django 5.1.7 on 2025-03-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_collectioninfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='short_name',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Short Country Name'),
        ),
    ]
