# Generated by Django 5.1.7 on 2025-03-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_country_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Legacy ID'),
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Country Description'),
        ),
        migrations.AddField(
            model_name='date',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Legacy ID'),
        ),
        migrations.AddField(
            model_name='load',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Legacy ID'),
        ),
        migrations.AddField(
            model_name='variation',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Legacy ID'),
        ),
    ]
