# Generated by Django 5.1.7 on 2025-05-19 17:58

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_box_legacy_id_country_description_date_legacy_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['caliber__code', 'name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='load',
            options={'ordering': ['headstamp__manufacturer__country__caliber__code', 'headstamp__manufacturer__country__name', 'headstamp__code', 'cart_id']},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['country__caliber__code', 'country__name', 'code']},
        ),
        migrations.AlterField(
            model_name='box',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.common_collection_image_path),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Country Code/Name'),
        ),
        migrations.AlterField(
            model_name='date',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.common_collection_image_path),
        ),
        migrations.AlterField(
            model_name='headstamp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.headstamp_image_path),
        ),
        migrations.AlterField(
            model_name='load',
            name='cart_id',
            field=models.CharField(max_length=20, verbose_name='Cartridge ID'),
        ),
        migrations.AlterField(
            model_name='load',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.common_collection_image_path),
        ),
        migrations.AlterField(
            model_name='variation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.common_collection_image_path),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('caliber', 'name')},
        ),
    ]
