# Generated by Django 5.1.7 on 2025-05-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_alter_country_options_alter_load_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['load__headstamp__manufacturer__country__caliber__code', 'load__headstamp__manufacturer__country__name', 'load__cart_id', 'year', 'lot_month']},
        ),
        migrations.AlterField(
            model_name='box',
            name='bid',
            field=models.CharField(max_length=20, verbose_name='Box ID'),
        ),
        migrations.AlterField(
            model_name='date',
            name='cart_id',
            field=models.CharField(max_length=20, verbose_name='Date/Lot ID'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='cart_id',
            field=models.CharField(max_length=20, verbose_name='Variation ID'),
        ),
    ]
