# Generated by Django 5.1.7 on 2025-05-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_alter_date_options_alter_box_bid_alter_date_cart_id_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['content_type', 'object_id'], name='collection__content_8ac318_idx'),
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['bid'], name='collection__bid_ee5f20_idx'),
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['updated_at'], name='collection__updated_208112_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['caliber'], name='collection__caliber_c5414c_idx'),
        ),
        migrations.AddIndex(
            model_name='date',
            index=models.Index(fields=['load'], name='collection__load_id_666dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='date',
            index=models.Index(fields=['cart_id'], name='collection__cart_id_cd1688_idx'),
        ),
        migrations.AddIndex(
            model_name='date',
            index=models.Index(fields=['load', 'cart_id'], name='collection__load_id_e781bf_idx'),
        ),
        migrations.AddIndex(
            model_name='date',
            index=models.Index(fields=['updated_at'], name='collection__updated_8ccd86_idx'),
        ),
        migrations.AddIndex(
            model_name='headstamp',
            index=models.Index(fields=['manufacturer'], name='collection__manufac_10f6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='headstamp',
            index=models.Index(fields=['manufacturer', 'code'], name='collection__manufac_a8f783_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['headstamp'], name='collection__headsta_308330_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['cart_id'], name='collection__cart_id_a258ae_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['headstamp', 'cart_id'], name='collection__headsta_1f3300_idx'),
        ),
        migrations.AddIndex(
            model_name='load',
            index=models.Index(fields=['updated_at'], name='collection__updated_0d5aab_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['country'], name='collection__country_a26a04_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturer',
            index=models.Index(fields=['country', 'code'], name='collection__country_8fdd66_idx'),
        ),
        migrations.AddIndex(
            model_name='variation',
            index=models.Index(fields=['load'], name='collection__load_id_46792f_idx'),
        ),
        migrations.AddIndex(
            model_name='variation',
            index=models.Index(fields=['date'], name='collection__date_id_6b172b_idx'),
        ),
        migrations.AddIndex(
            model_name='variation',
            index=models.Index(fields=['cart_id'], name='collection__cart_id_c06c79_idx'),
        ),
        migrations.AddIndex(
            model_name='variation',
            index=models.Index(fields=['updated_at'], name='collection__updated_75953d_idx'),
        ),
    ]
